Add ability to uninstall scheduler extender on OpenShift
dell/csi-baremetal pull request #103
Opened 2020-10-01 12:21 UTC by AnastasiaShemyakinskaya

## Purpose
Add uninstallation of scheduler for OpenShift
https://github.com/dell/csi-baremetal/issues/97

## PR checklist
- [ ] Add link to the issue
- [ ] Choose PR label
- [ ] New unit tests added
- [ ] Modified code has meaningful comments
- [ ] All TODOs are linked with issues
- [ ] All comments are resolved
- [ ] PR validation passed
- [ ] Custom CI passed

## Testing

2020-10-01 12:39 UTC, ykulazhenkov approved these changes

2020-10-02 07:38 UTC, mishoyama requested changes

2020-10-02 07:38 UTC, mishoyama commented on pkg/scheduler/patcher/openshift_patcher.sh
> +   Usage: openshift_patcher [--help] [--install] [--remove]
please use _--uninstall_ option instead of _--remove_

2020-10-02 12:52 UTC, mishoyama approved these changes

2020-10-02 14:50 UTC, merged