Remove pods in e2e tests in parallel to speed up tests
dell/csi-baremetal pull request #108
Opened 2020-10-05 10:49 UTC by ykulazhenkov

## Purpose
This change will speed up e2e testing
Add support for parallel PODs removal in e2e tests cleanup logic.

## PR checklist
- [ ] Add link to the issue
- [ ] Choose PR label
- [ ] New unit tests added
- [ ] Modified code has meaningful comments
- [ ] All TODOs are linked with issues
- [ ] All comments are resolved
- [ ] PR validation passed
- [ ] Custom CI passed

## Testing
_Link to custom CI build_

2020-10-05 11:15 UTC, rususlasan approved these changes

2020-10-05 19:05 UTC, mishoyama requested changes
Please create issue for this change.

2020-10-06 06:43 UTC, ykulazhenkov commented
Issue created https://github.com/dell/csi-baremetal/issues/110

2020-10-06 09:10 UTC, mishoyama approved these changes

2020-10-07 14:44 UTC, merged