[ISSUE-1153]: JSON validation for smart-info
dell/csi-baremetal pull request #1154
Opened 2024-05-15 12:29 UTC by korzepadawid

## Purpose
### Resolves #1153 

_Describe your changes_

## PR checklist
- [ ] Add link to the issue
- [ ] Choose Project
- [ ] Choose PR label
- [ ] New unit tests added
- [ ] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

## Testing
_Provide test details_

2024-05-17 09:02 UTC, katarzyna-kulpa requested changes

2024-05-17 09:02 UTC, katarzyna-kulpa commented on pkg/node/smart.go
> +		s.log.Errorf("Unable to parse a JSON returned from drivemgr: %v", smartInfoRawJSON)
Let's change slogan to: "Invalid Smart Info JSON response from drivemgr..."

2024-05-17 09:02 UTC, katarzyna-kulpa commented on pkg/node/smart.go
> +	smartInfoRawJSON := smartInfoResponse.GetSmartInfo()
do you see a possibility to extract duplicated code into the separate  method? this 3 lines smartInfoRawJSON := smartInfoResponse.GetSmartInfo()
	if !json.Valid([]byte(smartInfoRawJSON)) {
		s.log.Errorf("Unable to parse a JSON returned from drivemgr: %v", smartInfoRawJSON)
		can return true or false

2024-05-17 10:10 UTC, katarzyna-kulpa approved these changes

2024-05-20 08:04 UTC, mdutka-dell approved these changes

2024-05-20 08:04 UTC, merged