[ATL-27731] E2E tests CI/CD job for main
dell/csi-baremetal pull request #1205
Opened 2024-07-10 17:57 UTC by chaladak

## Purpose
### Resolves #

_Describe your changes_

## PR checklist
- [ ] Add link to the issue
- [ ] Choose Project
- [ ] Choose PR label
- [ ] New unit tests added
- [ ] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

## Testing
_Provide test details_

2024-07-11 05:24 UTC, korzepadawid requested changes

2024-07-11 05:24 UTC, korzepadawid commented on tests/e2e-test-framework/framework/propagating_thread.py
> +    #     super(PropagatingThread, self).join(timeout)
leftover?

2024-07-11 05:24 UTC, korzepadawid commented on tests/e2e-test-framework/framework/qtest_helper.py
> +        raise exception
question: why not `raise requests.HTTPError()`

2024-07-11 05:24 UTC, korzepadawid commented on tests/e2e-test-framework/framework/qtest_helper.py
> +        raise exception
any other scenario seems impossible

2024-07-11 05:24 UTC, korzepadawid commented on tests/e2e-test-framework/framework/qtest_helper.py
> +        raise exception
same as above

2024-07-11 05:24 UTC, korzepadawid commented on tests/e2e-test-framework/framework/qtest_helper.py
> +        raise exception
same as above

2024-07-11 05:24 UTC, korzepadawid commented on tests/e2e-test-framework/framework/qtest_helper.py
> +        raise exception
you could even raise it the except block, after the log

2024-07-11 05:24 UTC, korzepadawid commented on tests/e2e-test-framework/framework/ssh.py
> -class SSHCommandExecutor:
issue:  It shouldn't have been removed. It's a core class used by many other utils.

2024-07-11 05:24 UTC, korzepadawid commented on tests/e2e-test-framework/framework/ssh.py
> +class Ssh:
issue: It's unused.

2024-07-11 05:24 UTC, korzepadawid commented on tests/e2e-test-framework/requirements.txt
> +tox
issue: missing a tox's version

2024-07-11 08:09 UTC, korzepadawid approved these changes

2024-07-12 07:54 UTC, makowalcz approved these changes

2024-07-12 07:55 UTC, merged