[ISSUE-305] Label Management Proposal
dell/csi-baremetal pull request #306
Opened 2021-03-05 08:09 UTC by safronovD

## Purpose
### Issue #305 

Add label management proposal. Goals: 
- fix the error with incorrect label checking 
- remove additional annotations

## PR checklist
- [ ] Add link to the issue
- [ ] Choose PR label
- [ ] New unit tests added
- [ ] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

## Testing
_Link to custom CI build_

2021-03-10 09:41 UTC, mishoyama requested changes

2021-03-10 09:41 UTC, mishoyama commented on docs/proposals/label-management.md
> +2. Rename topologyKey:
No clear why we need to rename.

2021-03-11 08:31 UTC, mishoyama approved these changes

2021-03-11 08:39 UTC, AnastasiaShemyakinskaya approved these changes

2021-03-11 08:46 UTC, merged