[ISSUE-446] fake attach events
dell/csi-baremetal pull request #449
Opened 2021-06-29 22:51 UTC by yurkov-anton

### Issue #446

Add event FakeAttachEnabled, FakeAttachDisabled. Generated in NodeStageVolume and NodeUnstageVolume.

## PR checklist
- [X] Add link to the issue
- [ ] Choose PR label
- [ ] New unit tests added
- [ ] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

2021-06-30 08:40 UTC, mishoyama requested changes

2021-06-30 08:40 UTC, mishoyama commented on pkg/eventing/eventing.go
> +	FakeAttachEnabled  = "FakeAttachEnabled"
Please rename to `FakeAttachInvolved` and `FakeAttachCleared`

2021-06-30 08:40 UTC, mishoyama commented on docs/fake-attach.md
> +CSI must generate event to notify user about that Fake-Attach is enabled for this Volume.
Please add details about events and when they are generated.

2021-06-30 08:40 UTC, mishoyama commented on pkg/node/node.go
> +			"Fake-attach enable for volume with ID %s", volumeID)
_Fake-attach involved for volume with ID_

2021-06-30 08:40 UTC, mishoyama commented on pkg/node/node.go
> +			"Fake-attach disable for volume with ID %s", volumeID)
_Fake-attach cleared for volume with ID_

2021-06-30 08:41 UTC, safronovD commented on pkg/node/node.go
> +		s.VolumeManager.recorder.Eventf(volumeCR, eventing.NormalType, eventing.FakeAttachDisabled,
You should replace deleting the annotation and generating disable event to NodeStage. Or this event will appear each time when a related pod restarts

2021-07-02 08:15 UTC, safronovD approved these changes

2021-07-02 08:25 UTC, mishoyama approved these changes

2021-07-06 01:11 UTC, merged