[ISSUE-625] Add mount options support
dell/csi-baremetal pull request #630
Opened 2021-12-02 08:47 UTC by safronovD

## Purpose
### Resolves #625

- Check supported mount options on CreateVolume Request
- Add "noatime" option for Publish

## PR checklist
- [ ] Add link to the issue
- [ ] Choose Project
- [ ] Choose PR label
- [ ] New unit tests added
- [ ] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

## Testing
```
user@user-vm ~/g/s/g/d/csi-baremetal (feature-issue-625-add-mount-options-support)> kd sc
Name:                  csi-baremetal-sc
IsDefaultClass:        Yes
Annotations:           meta.helm.sh/release-name=csi-baremetal,meta.helm.sh/release-namespace=default,storageclass.kubernetes.io/is-default-class=true
Provisioner:           csi-baremetal
Parameters:            fsType=xfs,storageType=ANY
AllowVolumeExpansion:  <unset>
MountOptions:
  noatime
ReclaimPolicy:      Delete
VolumeBindingMode:  WaitForFirstConsumer
Events:             <none>

user@user-vm ~/g/s/g/dell> kgo volumes
NAME                                       SIZE        STORAGE CLASS   HEALTH   CSI_STATUS   OP_STATUS   USAGE    TYPE   LOCATION                               NODE
pvc-7c3e0bd4-eef2-4b3f-9afb-526224522c68   105906176   HDD             GOOD     PUBLISHED    OPERATIVE   IN_USE   xfs    aa804c75-49d2-48f8-adb6-944844c5b8ca   6bcf9136-4a7c-4a6e-ac09-32e09485db19
pvc-b6fdde0b-65b8-46b6-b076-d43f4a72747e   105906176   HDD             GOOD     PUBLISHED    OPERATIVE   IN_USE   xfs    db46ff55-06e0-43a6-b953-bf722f993e7c   6bcf9136-4a7c-4a6e-ac09-32e09485db19
pvc-eed07b95-9140-4c45-a16e-45466b102478   105906176   HDD             GOOD     PUBLISHED    OPERATIVE   IN_USE   xfs    fd6e5122-7da7-470b-adef-62c7b436d8a1   6bcf9136-4a7c-4a6e-ac09-32e09485db19

Dec  2 08:46:17.038 [DEBU] [Executor] [mount -o noatime /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-eed07b95-9140-4c45-a16e-45466b102478/globalmount/dev /var/lib/kubelet/pods/b29cf029-f14d-4336-9bd0-b3837e268f33/volumes/kubernetes.io~csi/pvc-eed07b95-9140-4c45-a16e-45466b102478/mount] [93.518338ms] [93518338] stdout: 
```

2021-12-02 09:29 UTC, mishoyama commented
/ci

2021-12-02 09:46 UTC, mishoyama requested changes
Can we have this feature documented?

2021-12-02 11:09 UTC, rkiselenko approved these changes

2021-12-03 09:33 UTC, mishoyama approved these changes

2021-12-06 08:31 UTC, merged