[ISSUE-641] upgrade kind to 0.11.1
dell/csi-baremetal pull request #642
Opened 2021-12-08 07:44 UTC by yurkov-anton

### Resolves #641

Upgrade kind from 0.8.1 to 0.11.1 in e2e tests.

## PR checklist
- [x] Add link to the issue
- [ ] Choose Project
- [x] Choose PR label
- [ ] New unit tests added
- [ ] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

## Testing
run tests

2021-12-08 07:47 UTC, safronovD approved these changes

2021-12-09 07:29 UTC, mishoyama requested changes

2021-12-09 07:29 UTC, mishoyama commented on variables.mk
> +KIND_VER := 0.11.1
Please remove version set from e2e workflow - https://github.com/dell/csi-baremetal/blob/master/.github/workflows/e2e.yml#L140

2021-12-10 09:12 UTC, yurkov-anton commented on variables.mk
> +KIND_VER := 0.11.1
removed

2021-12-10 14:42 UTC, mishoyama approved these changes

2021-12-10 17:38 UTC, merged