Bugfix reduce volume size in e2e expansion
dell/csi-baremetal pull request #726
Opened 2022-02-01 11:16 UTC by safronovD

## Purpose
### Resolves #

_Describe your changes_

## PR checklist
- [ ] Add link to the issue
- [ ] Choose Project
- [ ] Choose PR label
- [ ] New unit tests added
- [ ] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

## Testing
_Provide test details_

2022-02-02 12:32 UTC, mishoyama approved these changes

2022-02-02 12:33 UTC, misanthropicat approved these changes

2022-02-02 12:34 UTC, yurkov-anton approved these changes

2022-02-02 13:10 UTC, rkiselenko requested changes
There is a config file for kind `https://github.com/dell/csi-baremetal/blob/master/test/kind/small-kind.yaml` can we use only one, they looks the same.

2022-02-02 13:12 UTC, rkiselenko requested changes

2022-02-02 13:12 UTC, rkiselenko commented on test/e2e/common/deploy.go
> +		framework.Logf("Delete loopdevices in pod %s, stdout: %s, stderr: %s, err: %+v", pod, stdout, stderr, err)
The format here should be 
```golang
framework.Logf("Delete loopdevices in pod %+v, stdout: %s, stderr: %s, err: %w", pod, stdout, stderr, err)
```

2022-02-03 07:50 UTC, safronovD commented on test/e2e/common/deploy.go
> +		framework.Logf("Delete loopdevices in pod %s, stdout: %s, stderr: %s, err: %+v", pod, stdout, stderr, err)
I missed it, thanks!

2022-02-03 07:50 UTC, safronovD commented on test/e2e/common/deploy.go
> +		framework.Logf("Delete loopdevices in pod %s, stdout: %s, stderr: %s, err: %+v", pod, stdout, stderr, err)
Fixed

2022-02-03 07:53 UTC, safronovD commented
> There is a config file for kind https://github.com/dell/csi-baremetal/blob/master/test/kind/small-kind.yaml can we use only one, they looks the same.

We need to have 3 nodes for [some scheduler tests](https://github.com/dell/csi-baremetal/blob/ef03ca5edbb359f475dd3c3b9157e53380b18db9/test/e2e/scenarios/scheduler-test.go#L194) (kind.yaml). But in Github Action using 2+ nodes is not stable due to not enough memory (small-kind.yaml)

2022-02-03 09:00 UTC, rkiselenko approved these changes

2022-02-03 13:32 UTC, merged